Improve RestFieldsRegistry
csrui/wp-construct-plugin pull request #6
Opened 2019-01-08 18:37 UTC by csrui

- Check for ACF if not use WP functions
- Adds examples on documentation
- Changes the rest fields grouping key name (#3)

2019-01-11 15:36 UTC, xipasduarte commented on lib/ContentType/RestFieldsRegistry.php
> +				// If ACF detected, use it to retrieve metadata.
This is not something I believe you should be doing. You should assume WordPress meta fetching and naming structure. ACF requires you to be inside that mindset, here you are providing a sensible default, but for the fields that don't make sense using such a default, you have the custom callbacks, which put the strain on the developers to be aware of this.

Essentially you stop thinking about ACF, but add to the documentation how to handle complex types in it. Say a repeater, which generates lot's of meta fields, and whose main field only returns the number of entries, you would advise developers to use the `get_field()` as their callback, and not worry about it.

2019-01-11 15:37 UTC, xipasduarte requested changes
Take a look at Codacy's comments as well :)

2019-01-14 15:30 UTC, csrui commented on lib/ContentType/RestFieldsRegistry.php
> +				// If ACF detected, use it to retrieve metadata.
The goal is to support a commonly used library in a more automated way. Might need some refactoring to achieve total separation.

2019-01-14 15:39 UTC, xipasduarte approved these changes

2019-01-14 15:40 UTC, merged